### ISSUE TITLE
[20.10.06] Mapping failed with ACL groups Centreon and LDAP groups

### ISSUE THREAD

**Issue by AimPython** [centreon/centreon#9764]
# BUG REPORT INFORMATION

***Versions***

centreon-20.10.6-22.el7.centos.noarch
centreon-auto-discovery-server-20.10.3-2.el7.centos.noarch
centreon-base-config-centreon-engine-20.10.6-22.el7.centos.noarch
centreon-broker-20.10.4-5.el7.centos.x86_64
centreon-broker-cbd-20.10.4-5.el7.centos.x86_64
centreon-broker-cbmod-20.10.4-5.el7.centos.x86_64
centreon-broker-core-20.10.4-5.el7.centos.x86_64
centreon-broker-storage-20.10.4-5.el7.centos.x86_64
centreon-clib-20.10.1-2.el7.centos.x86_64
centreon-common-20.10.6-22.el7.centos.noarch
centreon-connector-20.10.0-2.el7.centos.x86_64
centreon-connector-perl-20.10.0-2.el7.centos.x86_64
centreon-connector-ssh-20.10.0-2.el7.centos.x86_64
centreon-database-20.10.6-22.el7.centos.noarch
centreon-engine-20.10.4-1.el7.centos.x86_64
centreon-engine-daemon-20.10.4-1.el7.centos.x86_64
centreon-engine-extcommands-20.10.4-1.el7.centos.x86_64
centreon-gorgone-20.10.3-1.el7.centos.noarch
centreon-gorgone-centreon-config-20.10.3-1.el7.centos.noarch
centreon-license-manager-20.10.2-1.el7.centos.noarch
centreon-license-manager-common-20.10.2-1.el7.centos.noarch
centreon-perl-libs-20.10.6-22.el7.centos.noarch
centreon-poller-centreon-engine-20.10.6-22.el7.centos.noarch
centreon-pp-manager-20.10.1-3.el7.centos.noarch
centreon-release-20.10-2.el7.centos.noarch
centreon-trap-20.10.6-22.el7.centos.noarch
centreon-web-20.10.6-22.el7.centos.noarch
centreon-widget-engine-status-20.10.0-5.el7.centos.noarch
centreon-widget-global-health-20.10.0-5.el7.centos.noarch
centreon-widget-graph-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-grid-map-20.10.0-5.el7.centos.noarch
centreon-widget-hostgroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-host-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-httploader-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-memory-usage-20.10.0-5.el7.centos.noarch
centreon-widget-servicegroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-service-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-tactical-overview-20.10.0-5.el7.centos.noarch

***Operating System***

CentOS7

***Browser used***

- [ ] Google Chrome
- [x] Firefox
- [ ] Internet Explorer IE11
- [ ] Safari

Version: 88.0 (64bit)

***Hypervisor***

Virtual server on Nutanix

### Description

When I add groups of related contacts in a Centreon ACL group, it stays there for a few seconds and then disappears.

### Steps to Reproduce

1 : Adding the LDAP linked contact group to the Centreon ACL group

![image](https://user-images.githubusercontent.com/77482495/116697773-e1fb6d00-a9c3-11eb-9c42-21b2a6e01687.png)
![image](https://user-images.githubusercontent.com/77482495/116697894-08b9a380-a9c4-11eb-9bf6-e130b793b2db.png)

A few seconds after :

![image](https://user-images.githubusercontent.com/77482495/116698140-5209f300-a9c4-11eb-9806-2ee7b894fed1.png)

### Describe the received result

It stays there for a few seconds and then disappears.

### Describe the expected result

The group should be linked.

### Logs
[]#tail -f /var/opt/rh/rh-php72/log/php-fpm/centreon-error.log
[30-Apr-2021 14:20:55] [critical] Uncaught Error: Class 'Centreon\Infrastructure\PlatformInformation\PlatformInformationRepositoryRDB' not found

[30-Apr-2021 14:20:55] [critical] Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\ClassNotFoundError: "Attempted to load class "PlatformInformationRepositoryRDB" from namespace "Centreon\Infrastructure\PlatformInformation".
Did you forget a "use" statement for another namespace?" at /var/cache/centreon/symfony/ContainerS3RsGBR/getPlatformInformationServiceInterfaceService.php line 13

[30-Apr-2021 14:20:56] [critical] Uncaught PHP Exception ReflectionException: "Property Centreon\Domain\Monitoring\ResourceExternalLinks::$notesUrl does not exist" at /usr/share/centreon/vendor/jms/metadata/src/Metadata/PropertyMetadata.php line 59

[30-Apr-2021 14:21:11] [critical] Uncaught PHP Exception ReflectionException: "Property Centreon\Domain\Monitoring\ResourceExternalLinks::$notesUrl does not exist" at /usr/share/centreon/vendor/jms/metadata/src/Metadata/PropertyMetadata.php line 59

[30-Apr-2021 14:22:56] PHP Warning:  sprintf(): Too few arguments in /usr/share/centreon/www/include/configuration/configObject/contact/ldapsearch.php on line 122

![image](https://user-images.githubusercontent.com/77482495/116696833-b330c700-a9c2-11eb-8780-fcc2ae82c20d.png)

[]# tail -f ldapsearch.log
[30/04/2021 14:50] LDAP Connect : trying url : ldap://XX.XX.XX:389/
[30/04/2021 14:50] LDAP Connect : Credentials : XX\XX_XX_XX_XX
[30/04/2021 14:51] LDAP Connect : trying url : ldap://XX.XX.XX:389/
[30/04/2021 14:51] LDAP Connect : Credentials : XX\XX_XX_XX_XX
[30/04/2021 14:56] LDAP Connect : trying url : ldap://XX.XX.XX:389/
[30/04/2021 14:56] LDAP Connect : Credentials : XX\XX_XX_XX_XX
[30/04/2021 14:56] LDAP Connect : trying url : ldap://XX.XX.XX:389/
[30/04/2021 14:56] LDAP Connect : Credentials : XX\XX_XX_XX_XX

**Found no log on ldap debugging for this bugs**

**Comment by AimPython** [comment]
Same after upgrading 20.04 to 21.04.
